@echo off
(echo AnneeAcademiqueController & echo no) | php bin/console make:crud AnneeAcademique
(echo AntecedentAcademiqueController & echo no) | php bin/console make:crud AntecedentAcademique
(echo BourseController & echo no) | php bin/console make:crud Bourse
(echo CampusController & echo no) | php bin/console make:crud Campus
(echo ChefDepartementController & echo no) | php bin/console make:crud ChefDepartement
(echo CoursController & echo no) | php bin/console make:crud Cours
(echo CycleController & echo no) | php bin/console make:crud Cycle
(echo DepartementController & echo no) | php bin/console make:crud Departement
(echo EvaluationController & echo no) | php bin/console make:crud Evaluation
(echo FiliereController & echo no) | php bin/console make:crud Filiere
(echo FiliereCycleController & echo no) | php bin/console make:crud FiliereCycle
(echo ImpressionFormatController & echo no) | php bin/console make:crud ImpressionFormat
(echo IncidentController & echo no) | php bin/console make:crud Incident
(echo InscriptionController & echo no) | php bin/console make:crud Inscription
(echo NoteController & echo no) | php bin/console make:crud Note
(echo PayementmethodController & echo no) | php bin/console make:crud Payementmethod
(echo PayementreasonController & echo no) | php bin/console make:crud Payementreason
(echo PlanningCoursController & echo no) | php bin/console make:crud PlanningCours
(echo PresenceController & echo no) | php bin/console make:crud Presence
(echo ProfesseurController & echo no) | php bin/console make:crud Professeur
(echo ReglementController & echo no) | php bin/console make:crud Reglement
(echo RoleController & echo no) | php bin/console make:crud Role
(echo SalleCoursController & echo no) | php bin/console make:crud SalleCours
(echo SemestreController & echo no) | php bin/console make:crud Semestre
(echo TuteurEtudiantController & echo no) | php bin/console make:crud TuteurEtudiant
(echo TypeEvaluationController & echo no) | php bin/console make:crud TypeEvaluation
(echo UEController & echo no) | php bin/console make:crud UE
(echo UtilisateurController & echo no) | php bin/console make:crud Utilisateur
